### ISSUE TITLE
Need add the .gitignore file into this repo

### ISSUE THREAD

**Issue by caoyongxu** [fileformat-words-gists/FileFormat.Words-for-.NET#2]
Thanks for providing this library, it's very helpful.

- Currently there is no .gitignore file in this repo, it causes there are too changes shown in the development environment after running the code.  
- I tried to remove the obj and bin sub folders under the two projects, the sample code still works as expect, so can we also delete the these folders? 

There are just suggestions, so please freely consider this.

**Comment by sabir-aspose** [comment]
@caoyongxu Apologies for a wrong delay in responding. A comprehensive .gitignore has been added: https://github.com/fileformat-words-gists/FileFormat.Words-for-.NET/commit/c8b140d2486565e6928d62688d64e0216f647b10

Plus folder structure has also been simplified.
